name: SonarCloud Scan 

on: 
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request
  push:
    branches:
      - "main"
      - "feature*"
jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Analyse with SonarCloud
      uses: sonarsource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
